Repository Total-RP/Total-RP-3-Extended, pull requests merged in 2024-07, with the labels that each got.

#248 Port over new Dropdowns + Small QoL
  totalRP3_Extended/Inventory/Inventory.xml
  totalRP3_Extended/Inventory/InventoryDrop.lua
  totalRP3_Extended/Inventory/InventoryPage.lua
  totalRP3_Extended/Locales/enUS.lua
  totalRP3_Extended/Quest/QuestLog.lua
  totalRP3_Extended/Security.lua
  totalRP3_Extended_Tools/Aura/Editor/Normal.lua
  totalRP3_Extended_Tools/Campaign/Editor/Normal.lua
  totalRP3_Extended_Tools/Campaign/Editor/Quest.lua
  totalRP3_Extended_Tools/Inner/Inner.lua
  totalRP3_Extended_Tools/List/List.lua
  totalRP3_Extended_Tools/Script/Conditions/Conditions.lua
  totalRP3_Extended_Tools/Script/Normal/Normal.lua
Labels: enhancement

#249 Update target and toolbar frame icons
  totalRP3_Extended/Inventory/Inspection.lua
  totalRP3_Extended/Inventory/InventoryDrop.lua
  totalRP3_Extended/Inventory/InventoryExchange.lua
  totalRP3_Extended/Misc/Sounds.lua
  totalRP3_Extended_Tools/List/List.lua
Labels: enhancement

#250 Settings dropdown consistency + English grammar
  totalRP3_Extended/Locales/deDE.lua
  totalRP3_Extended/Locales/enUS.lua
  totalRP3_Extended/Locales/esES.lua
  totalRP3_Extended/Locales/frFR.lua
  totalRP3_Extended/Locales/ptBR.lua
  totalRP3_Extended/Locales/ruRU.lua
  totalRP3_Extended/Locales/zhCN.lua
  totalRP3_Extended/Locales/zhTW.lua
  totalRP3_Extended/Main.lua
Labels: consistency

#251 Limit macro creation to 255 characters
  .luacheckrc
  totalRP3_Extended/Locales/deDE.lua
  totalRP3_Extended/Locales/enUS.lua
  totalRP3_Extended/Locales/frFR.lua
  totalRP3_Extended/Locales/zhCN.lua
  totalRP3_Extended_Tools/Script/Effects/Effects.lua
  totalRP3_Extended_Tools/Script/Effects/Effects.xml
Labels: enhancement

#252 Add missing semicolon to enUS localization
  totalRP3_Extended/Locales/enUS.lua
Labels: bug

#253 Fix broken localization script merge
  .github/scripts/localization.py
  totalRP3_Extended/Locales/deDE.lua
  totalRP3_Extended/Locales/enUS.lua
  totalRP3_Extended/Locales/esES.lua
  totalRP3_Extended/Locales/esMX.lua
  totalRP3_Extended/Locales/frFR.lua
  totalRP3_Extended/Locales/itIT.lua
  totalRP3_Extended/Locales/koKR.lua
  totalRP3_Extended/Locales/ptBR.lua
  totalRP3_Extended/Locales/ruRU.lua
  totalRP3_Extended/Locales/zhCN.lua
  totalRP3_Extended/Locales/zhTW.lua
Labels: bug

#255 Backdrop fixes
  .luacheckrc
  totalRP3_Extended/Inventory/Inventory.xml
  totalRP3_Extended/Quest/Quest.xml
  totalRP3_Extended/Quest/QuestObjective.lua
  totalRP3_Extended/Widgets.lua
  totalRP3_Extended_Tools/Inner/Inner.xml
  totalRP3_Extended_Tools/Links/Links.lua
  totalRP3_Extended_Tools/Links/Links.xml
  totalRP3_Extended_Tools/List/List.lua
  totalRP3_Extended_Tools/List/List.xml
  totalRP3_Extended_Tools/Main.lua
  totalRP3_Extended_Tools/Main.xml
  totalRP3_Extended_Tools/Script/Conditions/Conditions.lua
  totalRP3_Extended_Tools/Script/Element/Element.xml
Labels: bug

#254 11.0 updates
  .luacheckrc
  totalRP3_Extended/Dialogues/Dialogues.lua
  totalRP3_Extended/Inventory/Container.lua
  totalRP3_Extended/Inventory/Inspection.lua
  totalRP3_Extended/Inventory/Inventory.xml
  totalRP3_Extended/Inventory/InventoryExchange.lua
  totalRP3_Extended/Locales/enUS.lua
  totalRP3_Extended/Main.lua
  totalRP3_Extended/Main.xml
  totalRP3_Extended/Misc/Sounds.lua
  totalRP3_Extended/Quest/Quest.xml
  totalRP3_Extended/Quest/QuestObjective.lua
  totalRP3_Extended/UnitPopups.lua
  totalRP3_Extended/UnitPopups.xml
  totalRP3_Extended/Widgets.lua
  totalRP3_Extended_Tools/Aura/Aura.xml
  totalRP3_Extended_Tools/Aura/Effects.lua
  totalRP3_Extended_Tools/Campaign/Editor/Actions.lua
  totalRP3_Extended_Tools/Campaign/Editor/Actions.xml
  totalRP3_Extended_Tools/Cutscene/Editor/Normal.lua
  totalRP3_Extended_Tools/Cutscene/Editor/Normal.xml
  totalRP3_Extended_Tools/Document/Editor/Normal.lua
  totalRP3_Extended_Tools/Document/Editor/Normal.xml
  totalRP3_Extended_Tools/Inner/Inner.xml
  totalRP3_Extended_Tools/Items/Editor/Normal.lua
  totalRP3_Extended_Tools/Items/Editor/Normal.xml
  totalRP3_Extended_Tools/Items/Editor/Quick.lua
  totalRP3_Extended_Tools/Items/Editor/Quick.xml
  totalRP3_Extended_Tools/Items/Effects.lua
  totalRP3_Extended_Tools/Items/Items.xml
  totalRP3_Extended_Tools/Links/Links.lua
  totalRP3_Extended_Tools/Links/Links.xml
  totalRP3_Extended_Tools/List/List.lua
  totalRP3_Extended_Tools/List/List.xml
  totalRP3_Extended_Tools/Main.lua
  totalRP3_Extended_Tools/Main.xml
  totalRP3_Extended_Tools/Script/Conditions/Conditions.lua
  totalRP3_Extended_Tools/Script/Conditions/Conditions.xml
  totalRP3_Extended_Tools/Script/Conditions/Operands.lua
  totalRP3_Extended_Tools/Script/Conditions/Operands.xml
  totalRP3_Extended_Tools/Script/Effects/Effects.lua
  totalRP3_Extended_Tools/Script/Effects/Effects.xml
  totalRP3_Extended_Tools/Script/Element/Element.lua
  totalRP3_Extended_Tools/Script/Element/Element.xml
  totalRP3_Extended_Tools/Tutorial.lua
Labels: bug, enhancement

#258 Fix object browser after music browser rework
  totalRP3_Extended_Tools/Script/Element/Element.lua
  totalRP3_Extended_Tools/Script/Element/Element.xml
Labels: bug
